server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_homework?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  application:
    name: rabbit-producer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true
zuul:
  routes:
    #以微服务
    zuul-gateway: #路由id,随便写
      path: /person/** #映射路径  #localhost:8080/product-service/~
      serviceId: zuul-gateway #配置转发的微服务的服务名称
      url: http://localhost:8086