server:
  port: 8083
spring:
  application:
    name: rabbit-second-consumer
  rabbitmq:
    host: localhost
  cloud:
    stream:
      bindings:
        myInput:
          group: groupB
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/