server:
  port: 9000
spring:
  application:
    name: lab02-health-first-service-invoker
eureka:
  client:
    service-url:
      defaultZone: http://slave1:8761/eureka/
  instance:
    hostname: localhost