server:
  port: 9000
spring:
  application:
    name: lab04-first-service-invoker
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

lab04-first-service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFLoadBalancerPingClassName: com.MyPing
    listOfServers: http://localhost:8081,http://localhost:8085