server:
  port: 8081
spring:
  application:
    name: rabbit-consumer
  rabbitmq:
    host: localhost
  cloud:
    stream:
      bindings:
        myInput:
          group: groupA
        myinput2:
          destination: zuul
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/