server:
  port: 9000
spring:
  application:
    name: spring-hystrix-invoker
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://slave1:8761/eureka/
feign:
  hystrix:
    enabled: true