server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_homework?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  application:
    name: zuul-gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        myoutput:
          destination: zuul
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true
