spring:
  application:
    name: zuul-gateway
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    exceptionTest:
      path: /exceptionTest/**
    restTestRoute:
      path: /rest-tpl-sale/**
      serviceId: zuul-sale-service
#    sale:
#      path: /sale/**
#      serviceId: zuul-sale-service
    helloRoute:
      path: /test/**
      url: forward:/source/hello
#  SendForwardFilter:
#    route:
#      disable: true
management:
  endpoints:
    web:
      exposure:
        include: routes


