spring:
  application:
    name: lab02-fist-service-provider # 指定服务名
eureka:
  instance:
    hostname: localhost # eureka 服务端实例名称
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/