server:
  port: 9000
spring:
  application:
    name: lab-first-service-invoker
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://slave1:8761/eureka/,http://slave2:8762/eureka/